runtime: python311

# F4 instance class: 1GB memory (F2 is 512MB, not enough for ~290MB database)
instance_class: F4

# Automatic scaling - disabled (using Cloud Run instead)
automatic_scaling:
  min_instances: 0
  max_instances: 0
  target_cpu_utilization: 0.65

# Environment variables
env_variables:
  PORT: 8080
  DB_BUCKET_NAME: tak-explorer-db
