runtime: python311

# App Engine configuration
instance_class: F2  # 2GB memory, suitable for database processing

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

# Health check
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Environment variables
env_variables:
  PORT: 8080

# Network settings
network:
  forwarded_ports: [8080]

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
